language: ruby
sudo: false
cache: bundler

# Early warning system to catch if Rubygems breaks something
before_install:
  - gem update --system $(grep rubygems omnibus_overrides.rb | cut -d'"' -f2)
  - gem install bundler -v $(grep bundler omnibus_overrides.rb | cut -d'"' -f2)
  - rm -f .bundle/config

bundler_args: --without changelog development docgen guard maintenance omnibus_package tools aix bsd mac_os_x solaris windows --frozen

before_script:
 # force all .rspec tests into progress display to reduce line count
 - echo --color > .rspec
 - echo -fp >> .rspec
 # necessary for sudo: true tests, ingore failures on tests invoked with sudo: false
 - sudo sed -i -e 's/^Defaults\tsecure_path.*$//' /etc/sudoers || true

# do not run expensive spec tests on PRs, only on branches
branches:
  only:
  - master
  - 10-stable
  - 11-stable

env:
  global:
    - FORCE_FFI_YAJL=ext

matrix:
  include:
  - rvm: 2.2
    services: docker
    sudo: required
    gemfile: kitchen-tests/Gemfile
    before_install:
      - gem update --system $(grep rubygems omnibus_overrides.rb | cut -d'"' -f2)
      - gem install bundler -v $(grep bundler omnibus_overrides.rb | cut -d'"' -f2)
    before_script:
      - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
      - cd kitchen-tests
    script:
      - bundle exec kitchen test ubuntu-1204
    after_failure:
      - cat .kitchen/logs/kitchen.log
    env:
      - UBUNTU=1
      - KITCHEN_YAML=.kitchen.travis.yml
  - rvm: 2.2
    services: docker
    sudo: required
    gemfile: kitchen-tests/Gemfile
    before_install:
      - gem update --system $(grep rubygems omnibus_overrides.rb | cut -d'"' -f2)
      - gem install bundler -v $(grep bundler omnibus_overrides.rb | cut -d'"' -f2)
    before_script:
      - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
      - cd kitchen-tests
    script:
      - bundle exec kitchen test ubuntu-1404
    after_failure:
      - cat .kitchen/logs/kitchen.log
    env:
      - UBUNTU=1
      - KITCHEN_YAML=.kitchen.travis.yml
  - rvm: 2.2
    services: docker
    sudo: required
    gemfile: kitchen-tests/Gemfile
    before_install:
      - gem update --system $(grep rubygems omnibus_overrides.rb | cut -d'"' -f2)
      - gem install bundler -v $(grep bundler omnibus_overrides.rb | cut -d'"' -f2)
    before_script:
      - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
      - cd kitchen-tests
    script:
      - bundle exec kitchen test ubuntu-1604
    after_failure:
      - cat .kitchen/logs/kitchen.log
    env:
      - UBUNTU=1
      - KITCHEN_YAML=.kitchen.travis.yml
  - rvm: 2.2
    services: docker
    sudo: required
    gemfile: kitchen-tests/Gemfile
    before_install:
      - gem update --system $(grep rubygems omnibus_overrides.rb | cut -d'"' -f2)
      - gem install bundler -v $(grep bundler omnibus_overrides.rb | cut -d'"' -f2)
    before_script:
      - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
      - cd kitchen-tests
    script:
      - bundle exec kitchen test debian-7
    after_failure:
      - cat .kitchen/logs/kitchen.log
    env:
      - UBUNTU=1
      - KITCHEN_YAML=.kitchen.travis.yml
  - rvm: 2.2
    services: docker
    sudo: required
    gemfile: kitchen-tests/Gemfile
    before_install:
      - gem update --system $(grep rubygems omnibus_overrides.rb | cut -d'"' -f2)
      - gem install bundler -v $(grep bundler omnibus_overrides.rb | cut -d'"' -f2)
    before_script:
      - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
      - cd kitchen-tests
    script:
      - bundle exec kitchen test debian-8
    after_failure:
      - cat .kitchen/logs/kitchen.log
    env:
      - UBUNTU=1
      - KITCHEN_YAML=.kitchen.travis.yml
  - rvm: 2.2
    services: docker
    sudo: required
    gemfile: kitchen-tests/Gemfile
    before_install:
      - gem update --system $(grep rubygems omnibus_overrides.rb | cut -d'"' -f2)
      - gem install bundler -v $(grep bundler omnibus_overrides.rb | cut -d'"' -f2)
    before_script:
      - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
      - cd kitchen-tests
    script:
      - bundle exec kitchen test centos-5
    after_failure:
      - cat .kitchen/logs/kitchen.log
    env:
      - UBUNTU=1
      - KITCHEN_YAML=.kitchen.travis.yml
  - rvm: 2.2
    services: docker
    sudo: required
    gemfile: kitchen-tests/Gemfile
    before_install:
      - gem update --system $(grep rubygems omnibus_overrides.rb | cut -d'"' -f2)
      - gem install bundler -v $(grep bundler omnibus_overrides.rb | cut -d'"' -f2)
    before_script:
      - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
      - cd kitchen-tests
    script:
      - bundle exec kitchen test centos-6
    after_failure:
      - cat .kitchen/logs/kitchen.log
    env:
      - UBUNTU=1
      - KITCHEN_YAML=.kitchen.travis.yml
  - rvm: 2.2
    services: docker
    sudo: required
    gemfile: kitchen-tests/Gemfile
    before_install:
      - gem update --system $(grep rubygems omnibus_overrides.rb | cut -d'"' -f2)
      - gem install bundler -v $(grep bundler omnibus_overrides.rb | cut -d'"' -f2)
    before_script:
      - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
      - cd kitchen-tests
    script:
      - bundle exec kitchen test centos-7
    after_failure:
      - cat .kitchen/logs/kitchen.log
    env:
      - UBUNTU=1
      - KITCHEN_YAML=.kitchen.travis.yml
  - rvm: 2.2
    services: docker
    sudo: required
    gemfile: kitchen-tests/Gemfile
    before_install:
      - gem update --system $(grep rubygems omnibus_overrides.rb | cut -d'"' -f2)
      - gem install bundler -v $(grep bundler omnibus_overrides.rb | cut -d'"' -f2)
    before_script:
      - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
      - cd kitchen-tests
    script:
      - bundle exec kitchen test fedora-23
    after_failure:
      - cat .kitchen/logs/kitchen.log
    env:
      - UBUNTU=1
      - KITCHEN_YAML=.kitchen.travis.yml
  - rvm: 2.2
    services: docker
    sudo: required
    gemfile: kitchen-tests/Gemfile
    before_install:
      - gem update --system $(grep rubygems omnibus_overrides.rb | cut -d'"' -f2)
      - gem install bundler -v $(grep bundler omnibus_overrides.rb | cut -d'"' -f2)
    before_script:
      - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
      - cd kitchen-tests
    script:
      - bundle exec kitchen test opensuse-132
    after_failure:
      - cat .kitchen/logs/kitchen.log
    env:
      - UBUNTU=1
      - KITCHEN_YAML=.kitchen.travis.yml

  allow_failures:
    - rvm: 2.3.0
    - rvm: rbx

notifications:
  on_change: true
  on_failure: true
  on_success: change
  on_pull_requests: false
  irc:
    channels:
    - chat.freenode.net#chef-hacking
  webhooks:
    urls:
    # Gitter IM
    - secure: HmMKr/ysKVyKUJ24PRCHcA8QCmlFoukrYumY0GRLzvaFWO8PknHO1t/0RbrKRb2ed/hgkFd+RKNCYvSvcE8Ahr2vlMrBeGHGfVeOGkWtbhLgNqo1b50Ll9CqvTM8X2ZIq6hIWraanwoYRQu/8uGL29yH4lBi7DhpTkFwBMLulhQ=
  hipchat:
    rooms:
    # Build Statuses
    - secure: G8MNo94L8bmWWwkH2/ViB2QaZnZHZscYM/mEjDbOGd15sqrruwckeARyBoUcRI7P1C6AFmS4IKCNVXa6KzX4Pbh51gQWM92zRpRTZpplwtXz53/1l8ajLFLLMLvEMTlBFAANUKEUFAQPY4dMa14V3Qc5oijfIncN61k4nZNTKpY=
    # Open Source
    - secure: hmcex4PpG5dn8WvjndONO4xCUKOC5kPU/bUEGRrfVbe2YKJE7t0XXbNDC96W/xBgzgnJzvf1Er0zJKDrNf4qEDEWFoozdN00WLcqREgaLLS3Seto2FjR/BpBk5q+sCV0rwwEMms2P4Qk+VSnDCnm9EaeM55hOabqNuOrRzoZLBQ=
