---
driver:
  name: dokken
  privileged: true

transport:
  name: dokken

provisioner:
  name: chef_github
  chef_omnibus_url: "https://omnitruck.chef.io/install.sh"
  chef_omnibus_install_options: "-c current"
  github_owner: "chef"
  github_repo: "chef"
  refname: <%= ENV['TRAVIS_COMMIT'] %>
  github_access_token: <%= ENV['KITCHEN_GITHUB_TOKEN'] %>
  data_path: test/fixtures
# disable file provider diffs so we don't overflow travis' line limit
  client_rb:
    diff_disabled: true

verifier:
  name: inspec

platforms:
- name: debian-7
  driver:
    image: debian:7
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: debian-8
  driver:
    image: debian:8
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: centos-5
  driver:
    image: centos:5
    platform: rhel
    run_command: /sbin/init
    provision_command:
      - RUN yum clean all
      - RUN yum install -y which initscripts net-tools

- name: centos-6
  driver:
    image: centos:6
    intermediate_instructions:
      - RUN yum clean all
      - RUN yum -y install which initscripts net-tools

- name: centos-7
  driver:
    image: centos:7
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN yum clean all
      - RUN yum -y install which initscripts net-tools

- name: fedora-23
  driver:
    image: fedora:23
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN dnf -y install yum which initscripts net-tools

- name: ubuntu-12.04
  driver:
    image: ubuntu-upstart:12.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: ubuntu-14.04
  driver:
    image: ubuntu-upstart:14.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: ubuntu-16.04
  driver:
    image: ubuntu:16.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: opensuse-13.2
  driver:
    image: opensuse:13.2
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN zypper refresh

suites:
  - name: webapp
    run_list:
      - recipe[base::default]
#      - recipe[webapp::default]
