---
driver:
  name: dokken
  chef_version: latest
  privileged: true

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
    driver:
      image: ubuntu-upstart:14.04
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
  - name: centos-7
    driver:
      image: centos:7
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN yum -y install lsof

suites:
  - name: webapp
    run_list:
      - recipe[base::default]
      - recipe[webapp::default]
    attributes:
