source "https://supermarket.getchef.com"

cookbook "webapp", path: "cookbooks/webapp"
cookbook "base", path: "cookbooks/base"

cookbook "php", "~> 1.5.0"


cookbook "resolver", github: "chef-cookbooks/resolver", tag: "ba7edb12d86678557416fc657cd06c0bdebc1f4e"
