source "https://rubygems.org"

gem "ridley", github: "berkshelf/ridley"
gem "berkshelf"
gem "test-kitchen", "~> 1.4"
gem "kitchen-appbundle-updater"
gem "kitchen-vagrant", "~> 0.17"
gem "kitchen-ec2", github: "test-kitchen/kitchen-ec2"
gem "vagrant-wrapper"
